import { Poppins } from "next/font/google";
import "../styles/globals.css";
import { AuthProvider } from "@/contexts/auth-provider";

export const metadata = {
  title: "DOCA",
  description: "Generated by DOCA",
  icons: {
    icon: "/icons/doca-icon.svg",
    shortcut: "/icons/doca-icon.svg",
    apple: "/icons/doca-icon.svg",
  },
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className={poppins.className}>
      <body className="bg-white mx-auto">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
